-- AdlistQR Supabase Tablo Kurulum Script'i
-- Bu script, garson çağırma ve siparişler için gerekli olan tabloları oluşturur.

--
-- 1. Garson Çağırma Tablosu (`calls`)
-- Müşterilerin garson çağırma taleplerini saklar.
--
CREATE TABLE IF NOT EXISTS calls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id TEXT NOT NULL,
  table_id INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  -- Durumlar: 'pending' (beklemede), 'acknowledged' (görüldü), 'completed' (tamamlandı)
  status TEXT DEFAULT 'pending' NOT NULL
);

--
-- 2. Siparişler Tablosu (`orders`)
-- Müşterilerin verdiği siparişlerin detaylarını saklar.
--
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id TEXT NOT NULL,
  table_id INTEGER NOT NULL,
  -- Sipariş edilen ürünler (ürün id, adet, fiyat vb. bilgileri içerir)
  items JSONB NOT NULL,
  total_price NUMERIC(10, 2),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  -- Durumlar: 
  -- 'pending_approval' (Garson onayı bekliyor - QR'dan yeni geldi)
  -- 'received' (Garson onayladı, mutfağa gönderildi), 
  -- 'preparing' (hazırlanıyor), 
  -- 'ready' (hazır), 
  -- 'served' (servis edildi), 
  -- 'paid' (ödendi)
  status TEXT DEFAULT 'pending_approval' NOT NULL
);

--
-- 3. Menü Ürünleri Tablosu (`menu_items`)
-- Restoranın menüsündeki ürünleri saklar.
--
CREATE TABLE IF NOT EXISTS menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    category TEXT,
    image_url TEXT,
    is_available BOOLEAN DEFAULT TRUE NOT NULL
);

-- Örnek Veri Ekleme (İsteğe Bağlı)
-- Başlangıçta test için birkaç ürün ekleyebilirsiniz.
-- `your-restaurant-id` kısmını kendi işletme kimliğinizle değiştirmeyi unutmayın.
/*
INSERT INTO menu_items (restaurant_id, name, description, price, category, image_url) VALUES
('your-restaurant-id', 'Klasik Burger', '120g dana köftesi, özel sos, marul, domates', 250.00, 'Burgerler', 'https://example.com/images/burger.jpg'),
('your-restaurant-id', 'Margarita Pizza', 'Domates sos, mozzarella ve fesleğen', 280.50, 'Pizzalar', 'https://example.com/images/pizza.jpg'),
('your-restaurant-id', 'Coca-Cola', '330ml kutu', 50.00, 'İçecekler', 'https://example.com/images/cola.jpg');
*/

-- Gerçek zamanlı güncellemeler için tabloları yayına almayı unutmayın.
-- Supabase arayüzünden "Database" -> "Replication" bölümüne gidin ve
-- `calls` ve `orders` tabloları için "Source" olarak seçip yayını etkinleştirin. 